name: ci

on:
  push:
    branches:    
      - master
  pull_request:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13'
      - name: run-tests
        run: go test -v ./...
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: build-push-pr
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/3dhubs/github-deployment-resource:pr${{ github.event.number }}
      - name: build-push-master
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/3dhubs/github-deployment-resource:master
